name: 'Provision s3 backend'
on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - master
  #   paths:
  #   - 'profiles/vpc/*'
jobs:
  terraform_plan:
    name: 'Provision backend'
    env:
      TF_CLI_ARGS: '-no-color'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: 'profiles/s3-backend'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15
    - name: Terraform Fmt
      run: terraform fmt -check
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Apply
      run: terraform apply -auto-approve
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve -var-file="fixtures.tfvars"
    - name: Print the content of tfstate
      run: cat terraform.tfstate