name: 'Terraform CI'
on:
  push:
    branches:
    - master
    paths:
    - 'profiles/vpc/*'
jobs:
  terraform_plan:
    name: 'Terraform CI'
    env:
      TF_CLI_ARGS: '-no-color'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: 'profiles/vpc'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15
    - name: Terraform Fmt
      run: terraform fmt -check
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan -auto-approve -var-file="fixtures.tfvars"
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve -var-file="fixtures.tfvars"
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve -var-file="fixtures.tfvars"